### ISSUE TITLE
How is it possible to get the Verx Instance?

### ISSUE THREAD

**Issue by tbolis** [amoAHCP/spring-vertx-ext#11]
So far this extension is working great, I'm now stuck, I cannot figure out how to get the Vertx instance to use it to a @Configuration class for a @Bean, e.g.

```java
@Configuration
public Class AppConfig {
    @Bean
    public TestBean properties(Vertx instance) {
        return new TestBean(instance);
    }
}
```

Thanks

**Comment by amoAHCP** [comment]
Hi, I tink currently you can only use member injection to inject the Verticle (which gives you access to Vertx instance) ... or... to pass the Vertx instance from caller. I'll check if I can inject the Vertx instance on Spring context creation.

**Comment by tbolis** [comment]
Hello,

Member injection did not work as expected for me to configuration class, the following did **not** work

```java
@Configuration
public Class AppConfig {
    
    @Bean
    public TestBean properties(MyVerticle instance) {
        return new TestBean(instance.getVertx());
    }
}
```

Maybe after registering spring config class for Verticle's application context we can inject the instance of vertx like the following:

```java
// Register instance of vertx    
annotationConfigApplicationContext.getBeanFactory()
         .registerSingleton(io.vertx.core.Vertx.class.getCanonicalName(), vertx);`
```

I have created a similar VertxFactory, maybe If you want I can create a pull request for this

**Comment by amoAHCP** [comment]
Hi, I did this yesterday... have to do some additional Tests and will release a new version.

**Comment by tbolis** [comment]
Great Thanks
