### ISSUE TITLE
Allow Spring-context initialization without Vert.x Factory mechanism 

### ISSUE THREAD

**Issue by amoAHCP** [amoAHCP/spring-vertx-ext#13]
- No maven-shade  #config
- No "java-spring" prefix
- add static initializer and leave the rest as it  #is

**Comment by amoAHCP** [comment]
@Jotschi can you take a look at this? https://github.com/amoAHCP/spring-vertx-ext/commit/c580d000603cdeb01e98058c9cb3a826159eadfb

**Comment by Jotschi** [comment]
@amoAHCP Looks good to me although I'm no longer using spring-vertx-ext. I switched to dagger 2 a while ago.
